services:
  stt:
    build: .
    container_name: mira_stt
    devices:
      - /dev/snd:/dev/snd
    environment:
      - OLLAMA_URL=http://ollama:11434/api/generate
    depends_on:
      - ollama
    # Mount actions folder to allow editing scripts without rebuilding
    volumes:
      - ./actions:/app/actions

  ollama:
    image: ollama/ollama:latest
    container_name: mira_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./vosk-model-small-fr-0.22:/root/model_context
    # We might need to pull the model if it doesn't exist. 
    # For now, we assume the user has models or we'll need a script to pull them.
    # To use the custom 'mira' model, we need to create it inside this container.
    # See instructions in walkthrough.

volumes:
  ollama_data:
